version: "3"
volumes:
  tmp-shared:
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
     - "5002:5002"
    volumes:
      - tmp-shared:/tmp
    depends_on:
      - redis
  celery_queue:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    volumes:
      - tmp-shared:/tmp
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
